<?php
	/*
	 * Generates phantomjs-script.js
	 */

	require_once("libraries/generate_url.php");

	$id = rand(0, 100);
	$phantom = false;
	$fileName = generateFileName();
	$htmlFilePath = 'phantomjs_scripts/html_cache/' . $fileName . '.html'; //Relative to the shell process location

	if(!file_exists($htmlFilePath)) {
		$phantom = true;
		$scriptFileName = 'phantomjs_scripts/temp_phantomjs/' . $fileName . '.js'; //Relative to the shell process location
		$scriptCode = getResultCountCode();

		$fileContents = '/*
 * Main Phantomjs script
 * This file is auto generated by generate-phantomjs-script.php
 */

//Global variables
var url = "' . $url . '";
var userAgent = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36";
var htmlFilePath = "' . $htmlFilePath . '";
var injectedScriptPath = "../script-' . $scriptCode . '.js"; //Relative to the phantomjs script

//Loading Modules
var fs = require("fs");
var page = require("webpage").create();

//Changing page settings
page.settings.userAgent = userAgent;
page.settings.loadImages = false;

//Opening the page
page.open(url, function (status) {
	if (status === "success") {
		console.log("Connection successful");
		if(page.injectJs(injectedScriptPath)) { //Injecting script
			console.log("Script successfully injected");
		} else {
			console.log("Script injection failed");
			phantom.exit(1);
		}
	} else {
		console.log("Connection failed");
		phantom.exit(1);
	}

	page.onClosing = function(closingPage) {
		var path = htmlFilePath; //Setting the path for the HTML file
		var content = page.content;
		fs.write(path, content, "w");
		console.log("HTML file is created");
		phantom.exit(0);
	};
});';

		file_put_contents($scriptFileName, $fileContents);
	}

	function generateFileName() {
		global $query;
		$code = getResultCountCode();
		$name = $query['q'] . '-';

		$filePath400 = 'phantomjs_scripts/html_cache/' . $name . '400.html';
		$filePath500 = 'phantomjs_scripts/html_cache/' . $name . '500.html';
		$filePath800 = 'phantomjs_scripts/html_cache/' . $name . '800.html';

		if($code == 800) {
			$name = $name . $code;
			return $name;
		} else if($code == 500) {
			if(!file_exists($filePath800)) {
				$name = $name . $code;
				return $name;
			} else {
				$name = $name . '800';
				return $name;
			}
		} else if($code == 400) {
			if(!file_exists($filePath800)) {
				if(!file_exists($filePath500)) {
					$name = $name . $code;
					return $name;
				} else {
					$name = $name . '500';
					return $name;
				}
			} else {
				$name = $name . '800';
				return $name;
			}
		} else {
			if(!file_exists($filePath800)) {
				if(!file_exists($filePath500)) {
					if(!file_exists($filePath400)) {
						$name = $name . $code;
						return $name;
					} else {
						$name = $name . '400';
						return $name;
					}
				} else {
					$name = $name . '500';
					return $name;
				}
			} else {
				$name = $name . '800';
				return $name;
			}
		}
	}

	function getResultCountCode() {
		global $query;
		$lastResultNumber =  $query['start'] + $query['n'];
		if($lastResultNumber <= 100) {
			$code = 100;
		} else if ($lastResultNumber>100 && $lastResultNumber <= 400) {
			$code = 400;
		} else if ($lastResultNumber>400 && $lastResultNumber <= 500) {
			$code = 500;
		} else  {
			$code = 800;
		}
		return $code;
	}