<?php
/*
 * Generates phantomjs-script.js
 */

require_once("libraries/generate_url.php");

$id = rand(0, 100);
$scriptFileName = 'phantomjs_scripts/temp_phantomjs/phantomjs_script-' . $id . '.js'; //Relative to the shell process location
$htmlFilePath = 'phantomjs_scripts/temp_html/temp-' . $id . '.html'; //Relative to the shell process location

$fileContents = '/*
 * Main Phantomjs script
 * This file is auto generated by generate-phantomjs-script.php
 */

//Global variables
var url = "' . $url . '";
var userAgent = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36";
var htmlFilePath = "' . $htmlFilePath . '";
var injectedScriptPath = "../script.js"; //Relative to the phantomjs script

//Loading Modules
var fs = require("fs");
var page = require("webpage").create();

//Changing page settings
page.settings.userAgent = userAgent;
page.settings.loadImages = false;

//Opening the page
page.open(url, function (status) {
	if (status === "success") {
		console.log("Connection successful");
		if(page.injectJs(injectedScriptPath)) { //Injecting script
			console.log("Script successfully injected");
		} else {
			console.log("Script injection failed");
			phantom.exit(1);
		}
	} else {
		console.log("Connection failed");
		phantom.exit(1);
	}
	
	page.onClosing = function(closingPage) {
		var path = htmlFilePath; //Setting the path for the HTML file
		var content = page.content;
		fs.write(path, content, "w");
		console.log("HTML file is created");
		phantom.exit(0);
	};
});';

file_put_contents($scriptFileName, $fileContents);